# Render Blueprint for RentEase Nepal backend API
# Docs: https://render.com/docs/blueprint-spec

services:
  - type: web
    name: rentease-nepal-api
    runtime: node
    plan: free
    region: singapore
    branch: master
    rootDir: server
    buildCommand: npm install && mkdir -p public/uploads
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URL
        value: mongodb+srv://rentease_admin:jeJwsMTWpcEM5eGx@cluster0.iwgxscu.mongodb.net/rentease_admin?appName=Cluster0
      - key: MONGO_DB_NAME
        value: rentease_admin
      - key: JWT_SECRET
        value: KwjHI7UedIdcM8BYeLosXKIQxEzUNzhk
      - key: GOOGLE_CLIENT_ID
        value: 963679257311-ek9ereusnmh5m413mi5dek7ka93fu3ab.apps.googleusercontent.com
      - key: GOOGLE_CLIENT_SECRET
        value: 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
      - key: CLIENT_URL
        value: http://localhost:3000
